In [42]:
import geopandas as gpd
import pandas as pd

In [43]:
gdf_grids = gpd.read_file('Data/Generated_grids/square_grids1000.shp')

In [44]:
gdf_grids.columns

Index(['grid_id', 'area', 'centroid', 'index_righ', 'CODEMAMROT', 'NOM',
       'TYPE', 'ABREV', 'int_area', 'geometry'],
      dtype='object')

In [45]:
gdf_boroughs = gpd.read_file('Data/Boroughs/LIMADMIN.shp')

In [46]:
gdf_boroughs.columns

Index(['MUNID', 'CODEID', 'CODEMAMROT', 'NOM', 'TYPE', 'ABREV', 'NUM', 'AIRE',
       'PERIM', 'geometry'],
      dtype='object')

In [47]:
gdf_boroughs.head(34)

,MUNID,CODEID,CODEMAMROT,NOM,TYPE,ABREV,NUM,AIRE,PERIM,geometry
0,66023,11,REM05,Outremont,Arrondissement,OM,5,3.813356e+06,10836.670,"POLYGON ((-73.62078 45.52365, -73.62020 45.524..."
1,66023,22,REM17,LaSalle,Arrondissement,LS,18,2.519727e+07,25259.849,"POLYGON ((-73.66610 45.42180, -73.66601 45.428..."
2,66023,62,66072,Mont-Royal,Ville liée,MR,2,7.445560e+06,18314.038,"POLYGON ((-73.65075 45.52631, -73.65036 45.526..."
3,66023,9,REM19,Ville-Marie,Arrondissement,VM,20,2.150063e+07,26585.959,"POLYGON ((-73.53013 45.53476, -73.53019 45.534..."
4,66023,5,REM21,Le Plateau-Mont-Royal,Arrondissement,PM,22,8.151665e+06,13158.328,"POLYGON ((-73.55923 45.53990, -73.56017 45.538..."
5,66023,54,66062,Hampstead,Ville liée,HS,10,1.768055e+06,5875.848,"POLYGON ((-73.65601 45.47893, -73.65601 45.481..."
6,66023,63,REM20,Le Sud-Ouest,Arrondissement,SO,21,1.814427e+07,29633.161,"POLYGON ((-73.62908 45.44839, -73.63197 45.449..."
7,66023,57,REM33,Rivière-des-Prairies-Pointe-aux-Trembles,Arrondissement,RP,19,5.004700e+07,38573.067,"POLYGON ((-73.62475 45.63359, -73.62469 45.633..."
8,66023,28,REM27,Lachine,Arrondissement,LC,17,2.312779e+07,25399.526,"POLYGON ((-73.72299 45.42179, -73.72085 45.438..."
9,66023,51,66087,Dorval,Ville liée,DV,1,2.815615e+07,32357.566,"POLYGON ((-73.79470 45.48181, -73.78960 45.484..."
10,66023,2,REM16,Montréal-Nord,Arrondissement,MN,16,1.243021e+07,16416.941,"POLYGON ((-73.65430 45.58363, -73.65444 45.583..."
11,66023,39,REM32,L'Île-Bizard-Sainte-Geneviève,Arrondissement,IS,6,3.653251e+07,28399.248,"POLYGON ((-73.97435 45.46643, -73.97285 45.467..."
12,66023,59,66102,Kirkland,Ville liée,KL,3,9.687581e+06,17837.584,"POLYGON ((-73.90124 45.43535, -73.90132 45.435..."
13,66023,65,66142,Dollard-des-Ormeaux,Ville liée,DO,11,1.506516e+07,21358.343,"POLYGON ((-73.85456 45.47060, -73.85517 45.471..."
14,66023,43,66127,Senneville,Ville liée,SV,77,1.860996e+07,21837.310,"POLYGON ((-73.96071 45.40618, -73.96079 45.406..."
15,66023,4,REM23,Ahuntsic-Cartierville,Arrondissement,AC,24,2.557119e+07,37790.097,"POLYGON ((-73.76363 45.51193, -73.76354 45.511..."
16,66023,56,66058,Côte-Saint-Luc,Ville liée,CL,72,6.810210e+06,16248.554,"MULTIPOLYGON (((-73.67721 45.48369, -73.67630 ..."
17,66023,6,REM14,Saint-Léonard,Arrondissement,LN,14,1.355069e+07,16325.544,"POLYGON ((-73.62877 45.58323, -73.62894 45.583..."
18,66023,52,66047,Montréal-Ouest,Ville liée,MO,75,1.419449e+06,7276.142,"POLYGON ((-73.66817 45.45655, -73.66807 45.456..."
19,66023,47,66097,Pointe-Claire,Ville liée,PC,8,3.444652e+07,27073.297,"POLYGON ((-73.83828 45.44540, -73.83215 45.445..."
20,66023,50,66092,L'Île-Dorval,Ville liée,ID,73,1.805089e+05,1814.424,"POLYGON ((-73.73990 45.43059, -73.74015 45.430..."
21,66023,10,REM22,Mercier-Hochelaga-Maisonneuve,Arrondissement,MH,23,2.740841e+07,33178.813,"POLYGON ((-73.50688 45.61065, -73.50693 45.610..."
22,66023,61,REM34,Côte-des-Neiges-Notre-Dame-de-Grâce,Arrondissement,CN,27,2.148375e+07,35557.954,"POLYGON ((-73.67721 45.48369, -73.67628 45.487..."
23,66023,8,REM24,Rosemont-La Petite-Patrie,Arrondissement,RO,25,1.588653e+07,19394.163,"POLYGON ((-73.58715 45.56642, -73.58689 45.566..."
24,66023,29,REM15,Saint-Laurent,Arrondissement,LR,15,4.307785e+07,36589.407,"POLYGON ((-73.77362 45.49820, -73.77238 45.498..."
25,66023,46,66107,Beaconsfield,Ville liée,BF,7,2.492251e+07,23295.573,"POLYGON ((-73.89453 45.41015, -73.89559 45.414..."
26,66023,66,REM25,Villeray-Saint-Michel-Parc-Extension,Arrondissement,VS,26,1.647736e+07,21180.049,"POLYGON ((-73.63652 45.57600, -73.63649 45.576..."
27,66023,64,66032,Westmount,Ville liée,WM,4,4.016301e+06,8959.397,"POLYGON ((-73.60684 45.49528, -73.60491 45.494..."
28,66023,60,66007,Montréal-Est,Ville liée,ME,74,1.397401e+07,16860.148,"POLYGON ((-73.49190 45.63286, -73.48411 45.631..."
29,66023,7,REM09,Anjou,Arrondissement,AJ,9,1.387819e+07,18275.947,"POLYGON ((-73.60235 45.61259, -73.60142 45.612..."
30,66023,38,REM31,Pierrefonds-Roxboro,Arrondissement,PR,13,3.376527e+07,51360.092,"POLYGON ((-73.97435 45.46643, -73.95671 45.468..."
31,66023,44,66117,Sainte-Anne-de-Bellevue,Ville liée,BV,76,1.115055e+07,19274.046,"POLYGON ((-73.93415 45.39883, -73.93478 45.398..."
32,66023,16,REM12,Verdun,Arrondissement,VD,12,2.232867e+07,20314.697,"POLYGON ((-73.53986 45.42801, -73.58389 45.435..."
33,66023,45,66112,Baie-d'Urfé,Ville liée,BU,71,8.025921e+06,11652.905,"POLYGON ((-73.89453 45.41015, -73.89464 45.410..."

In [48]:
df_property_assessment = pd.read_csv(
    'Data/Processed_Datasets/Cleaned_datasets/df_property_assessment.csv')

In [49]:
df_fe_stc = gdf_grids.loc[:, ['CODEMAMROT']].drop_duplicates()

In [50]:
df_fe_stc.shape

(34, 1)

### Number of property assessments per borough or affiliated city

In [51]:
pa_counts = df_property_assessment.groupby(
    'CODEMAMROT').size().reset_index(name='PROPERTY_ASSESSMENT_COUNT')

In [52]:
df_fe_stc = df_fe_stc.merge(pa_counts,
                            on='CODEMAMROT',
                            how='left')

In [53]:
df_fe_stc.describe(include='all')

       CODEMAMROT  PROPERTY_ASSESSMENT_COUNT
count          34                  34.000000
unique         34                        NaN
top         REM33                        NaN
freq            1                        NaN
mean          NaN               14752.676471
std           NaN               11692.637165
min           NaN                  74.000000
25%           NaN                6179.500000
50%           NaN               11948.500000
75%           NaN               25930.250000
max           NaN               42241.000000

### Number of property assessments per borough or affiliated city for each UEF category

In [54]:
# Store a dataframe without the 'Infrastructure' type
df_pa = df_property_assessment[df_property_assessment['CATEGORIE_UEF']
                               != 'Infrastructure']

In [55]:
pa_counts = pd.pivot_table(df_pa, index='CODEMAMROT',
                           columns='CATEGORIE_UEF', values='ID_UEV', aggfunc='count')
pa_counts.columns = [
    f'{col}_PROPERTY_ASSESSMENT_COUNT' for col in pa_counts.columns]
df_fe_stc = df_fe_stc.join(pa_counts, on='CODEMAMROT')
df_fe_stc = df_fe_stc.fillna(0)

In [56]:
df_fe_stc.describe(include='all')

,CODEMAMROT,PROPERTY_ASSESSMENT_COUNT,Condominium_PROPERTY_ASSESSMENT_COUNT,Régulier_PROPERTY_ASSESSMENT_COUNT
count,34,34.000000,34.000000,34.000000
unique,34,NaN,NaN,NaN
top,REM33,NaN,NaN,NaN
freq,1,NaN,NaN,NaN
mean,NaN,14752.676471,5383.970588,9368.676471
std,NaN,11692.637165,6963.531442,7029.162650
min,NaN,74.000000,0.000000,74.000000
25%,NaN,6179.500000,495.500000,4345.500000
50%,NaN,11948.500000,3150.500000,7914.000000
75%,NaN,25930.250000,8430.750000,12712.250000
max,NaN,42241.000000,34920.000000,25557.000000

### Average height above ground per borough or affiliated city

In [57]:
df_pa = df_property_assessment.dropna(subset=['ETAGE_HORS_SOL'])

In [58]:
df_grouped_avg_height= df_pa.groupby('CODEMAMROT')['ETAGE_HORS_SOL'].mean().rename('HEIGHT_ABOVE_GROUND_MEAN').reset_index()
print(df_grouped_avg_height)

   CODEMAMROT  HEIGHT_ABOVE_GROUND_MEAN
0       66007                  1.511873
1       66032                  1.906144
2       66047                  1.883526
3       66058                  1.515746
4       66062                  1.834877
5       66072                  1.755742
6       66087                  1.349052
7       66092                  1.052632
8       66097                  1.627905
9       66102                  1.868810
10      66107                  1.659620
11      66112                  1.564505
12      66117                  1.812587
13      66127                  1.553371
14      66142                  1.719910
15      REM05                  1.705458
16      REM09                  1.561592
17      REM12                  1.631122
18      REM14                  1.740404
19      REM15                  1.596520
20      REM16                  1.813226
21      REM17                  1.696316
22      REM19                  1.469965
23      REM20                  1.544283
24      REM21                  1.889452
25      REM22                  1.808032
26      REM23                  1.660606
27      REM24                  1.812299
28      REM25                  1.887458
29      REM27                  1.769514
30      REM31                  1.549198
31      REM32                  1.645650
32      REM33                  1.545188
33      REM34                  1.811998

In [59]:
df_fe_stc = df_fe_stc.merge(df_grouped_avg_height,
                            on='CODEMAMROT',
                            how='left')

In [60]:
df_fe_stc = df_fe_stc.fillna(0)

In [61]:
df_fe_stc.describe(include='all')

,CODEMAMROT,PROPERTY_ASSESSMENT_COUNT,Condominium_PROPERTY_ASSESSMENT_COUNT,Régulier_PROPERTY_ASSESSMENT_COUNT,HEIGHT_ABOVE_GROUND_MEAN
count,34,34.000000,34.000000,34.000000,34.000000
unique,34,NaN,NaN,NaN,NaN
top,REM33,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN
mean,NaN,14752.676471,5383.970588,9368.676471,1.669252
std,NaN,11692.637165,6963.531442,7029.162650,0.178831
min,NaN,74.000000,0.000000,74.000000,1.052632
25%,NaN,6179.500000,495.500000,4345.500000,1.555426
50%,NaN,11948.500000,3150.500000,7914.000000,1.678461
75%,NaN,25930.250000,8430.750000,12712.250000,1.812223
max,NaN,42241.000000,34920.000000,25557.000000,1.906144

### Average dwelling found in property assessments per borough or affiliated city

In [62]:
df_pa = df_property_assessment.dropna(subset=['NOMBRE_LOGEMENT'])

In [63]:
df_grouped_avg_dwelling = df_pa.groupby('CODEMAMROT')['NOMBRE_LOGEMENT'].mean(
).rename('DWELLING_MEAN').reset_index()
print(df_grouped_avg_dwelling)

   CODEMAMROT  DWELLING_MEAN
0       66007       2.120000
1       66032       1.937931
2       66047       1.313609
3       66058       2.105851
4       66062       1.468920
5       66072       1.479409
6       66087       1.549345
7       66092       1.000000
8       66097       1.434260
9       66102       1.061324
10      66107       1.061777
11      66112       1.057791
12      66117       1.582163
13      66127       1.106017
14      66142       1.251707
15      REM05       1.807292
16      REM09       2.069064
17      REM12       2.131014
18      REM14       2.766502
19      REM15       1.887186
20      REM16       3.037400
21      REM17       2.291821
22      REM19       2.296771
23      REM20       2.011925
24      REM21       2.861847
25      REM22       2.512385
26      REM23       2.392301
27      REM24       2.680339
28      REM25       2.928525
29      REM27       2.101962
30      REM31       1.365384
31      REM32       1.291819
32      REM33       1.526914
33      REM34       3.423563

In [64]:
df_fe_stc = df_fe_stc.merge(df_grouped_avg_dwelling,
                            on='CODEMAMROT',
                            how='left')

In [65]:
df_fe_stc = df_fe_stc.fillna(0)

In [66]:
df_fe_stc.describe(include='all')

,CODEMAMROT,PROPERTY_ASSESSMENT_COUNT,Condominium_PROPERTY_ASSESSMENT_COUNT,Régulier_PROPERTY_ASSESSMENT_COUNT,HEIGHT_ABOVE_GROUND_MEAN,DWELLING_MEAN
count,34,34.000000,34.000000,34.000000,34.000000,34.000000
unique,34,NaN,NaN,NaN,NaN,NaN
top,REM33,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,14752.676471,5383.970588,9368.676471,1.669252,1.909239
std,NaN,11692.637165,6963.531442,7029.162650,0.178831,0.652216
min,NaN,74.000000,0.000000,74.000000,1.052632,1.000000
25%,NaN,6179.500000,495.500000,4345.500000,1.555426,1.382603
50%,NaN,11948.500000,3150.500000,7914.000000,1.678461,1.912559
75%,NaN,25930.250000,8430.750000,12712.250000,1.812223,2.295534
max,NaN,42241.000000,34920.000000,25557.000000,1.906144,3.423563

### Average construction year (void years after 2023) per borough or affiliated city

In [67]:
df_pa = df_property_assessment[df_property_assessment['ANNEE_CONSTRUCTION'] <= 2023]

In [68]:
# Mean construction year per district
df_grouped_avg_construction_year = df_pa.groupby('CODEMAMROT')['ANNEE_CONSTRUCTION'].mean(
).rename('CONSTRUCTION_YEAR_MEAN').reset_index()
print(df_grouped_avg_construction_year)

   CODEMAMROT  CONSTRUCTION_YEAR_MEAN
0       66007             1964.521849
1       66032             1932.048753
2       66047             1940.835907
3       66058             1975.123788
4       66062             1959.786725
5       66072             1962.710614
6       66087             1970.901922
7       66092             1940.210526
8       66097             1973.496250
9       66102             1983.986846
10      66107             1968.710984
11      66112             1967.930314
12      66117             1967.026174
13      66127             1952.226471
14      66142             1978.006600
15      REM05             1938.635473
16      REM09             1980.722426
17      REM12             1972.693531
18      REM14             1978.315957
19      REM15             1983.977006
20      REM16             1966.620623
21      REM17             1978.660199
22      REM19             1979.474658
23      REM20             1972.690572
24      REM21             1937.150205
25      REM22             1965.688236
26      REM23             1968.688832
27      REM24             1961.031379
28      REM25             1958.482755
29      REM27             1966.249957
30      REM31             1979.097838
31      REM32             1982.695015
32      REM33             1983.395485
33      REM34             1957.799074

In [69]:
df_fe_stc = df_fe_stc.merge(df_grouped_avg_construction_year,
                            on='CODEMAMROT',
                            how='left')

In [70]:
df_fe_stc = df_fe_stc.fillna(0)

In [71]:
df_fe_stc.describe(include='all')

,CODEMAMROT,PROPERTY_ASSESSMENT_COUNT,Condominium_PROPERTY_ASSESSMENT_COUNT,Régulier_PROPERTY_ASSESSMENT_COUNT,HEIGHT_ABOVE_GROUND_MEAN,DWELLING_MEAN,CONSTRUCTION_YEAR_MEAN
count,34,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000
unique,34,NaN,NaN,NaN,NaN,NaN,NaN
top,REM33,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,14752.676471,5383.970588,9368.676471,1.669252,1.909239,1966.164498
std,NaN,11692.637165,6963.531442,7029.162650,0.178831,0.652216,14.510131
min,NaN,74.000000,0.000000,74.000000,1.052632,1.000000,1932.048753
25%,NaN,6179.500000,495.500000,4345.500000,1.555426,1.382603,1960.097888
50%,NaN,11948.500000,3150.500000,7914.000000,1.678461,1.912559,1968.309573
75%,NaN,25930.250000,8430.750000,12712.250000,1.812223,2.295534,1978.238618
max,NaN,42241.000000,34920.000000,25557.000000,1.906144,3.423563,1983.986846

### Average land area (m2) per borough or affiliated city

In [72]:
df_pa = df_property_assessment.dropna(subset=['SUPERFICIE_TERRAIN'])

In [73]:
df_grouped_avg_land_area = df_pa.groupby('CODEMAMROT')['SUPERFICIE_TERRAIN'].mean(
).rename('LAND_AREA_MEAN').reset_index()
print(df_grouped_avg_land_area)

   CODEMAMROT  LAND_AREA_MEAN
0       66007     8320.717742
1       66032      523.243367
2       66047      661.359606
3       66058      796.065181
4       66062      665.220986
5       66072      861.466750
6       66087     2532.455302
7       66092     2441.256757
8       66097     1317.279161
9       66102     1200.200483
10      66107     1209.883205
11      66112     3125.256887
12      66117     5728.167168
13      66127    13474.906615
14      66142      796.601633
15      REM05      474.270036
16      REM09      973.738217
17      REM12      402.040483
18      REM14      758.332242
19      REM15     1373.713573
20      REM16      560.342243
21      REM17      704.992400
22      REM19      319.157880
23      REM20      487.410665
24      REM21      218.302654
25      REM22      607.894980
26      REM23      602.361625
27      REM24      354.549482
28      REM25      464.919686
29      REM27     1214.685191
30      REM31     1083.008362
31      REM32     3437.354648
32      REM33     1029.529479
33      REM34      591.410351

In [74]:
df_fe_stc = df_fe_stc.merge(df_grouped_avg_land_area,
                            on='CODEMAMROT',
                            how='left')

In [75]:
df_fe_stc = df_fe_stc.fillna(0)

In [76]:
df_fe_stc.describe(include='all')

,CODEMAMROT,PROPERTY_ASSESSMENT_COUNT,Condominium_PROPERTY_ASSESSMENT_COUNT,Régulier_PROPERTY_ASSESSMENT_COUNT,HEIGHT_ABOVE_GROUND_MEAN,DWELLING_MEAN,CONSTRUCTION_YEAR_MEAN,LAND_AREA_MEAN
count,34,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000
unique,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,REM33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,14752.676471,5383.970588,9368.676471,1.669252,1.909239,1966.164498,1744.473383
std,NaN,11692.637165,6963.531442,7029.162650,0.178831,0.652216,14.510131,2651.686684
min,NaN,74.000000,0.000000,74.000000,1.052632,1.000000,1932.048753,218.302654
25%,NaN,6179.500000,495.500000,4345.500000,1.555426,1.382603,1960.097888,568.109270
50%,NaN,11948.500000,3150.500000,7914.000000,1.678461,1.912559,1968.309573,796.333407
75%,NaN,25930.250000,8430.750000,12712.250000,1.812223,2.295534,1978.238618,1291.630669
max,NaN,42241.000000,34920.000000,25557.000000,1.906144,3.423563,1983.986846,13474.906615

### Average building area (m2) per borough or affiliated city

In [77]:
df_pa = df_property_assessment.dropna(subset=['SUPERFICIE_BATIMENT'])

In [78]:
df_grouped_avg_building_area = df_pa.groupby('CODEMAMROT')['SUPERFICIE_BATIMENT'].mean(
).rename('BUILDING_AREA_MEAN').reset_index()
print(df_grouped_avg_building_area)

   CODEMAMROT  BUILDING_AREA_MEAN
0       66007          602.407966
1       66032         1395.991012
2       66047          218.814766
3       66058         1473.793512
4       66062          300.139693
5       66072          654.273231
6       66087          454.959005
7       66092          100.568966
8       66097          310.166871
9       66102          284.105708
10      66107          228.496283
11      66112          364.019383
12      66117          557.784615
13      66127          315.765043
14      66142          267.512797
15      REM05          809.643747
16      REM09         1056.200716
17      REM12         1249.160882
18      REM14          466.943374
19      REM15          847.813642
20      REM16          331.110782
21      REM17          681.754672
22      REM19         1720.661188
23      REM20         1181.057356
24      REM21         1362.174027
25      REM22          521.481488
26      REM23         2226.556192
27      REM24          738.912896
28      REM25          608.763464
29      REM27          467.044265
30      REM31          229.336926
31      REM32          249.033867
32      REM33          393.372092
33      REM34          988.845238

In [79]:
df_fe_stc = df_fe_stc.merge(df_grouped_avg_building_area,
                            on='CODEMAMROT',
                            how='left')

In [80]:
df_fe_stc = df_fe_stc.fillna(0)

In [81]:
df_fe_stc.describe(include='all')

,CODEMAMROT,PROPERTY_ASSESSMENT_COUNT,Condominium_PROPERTY_ASSESSMENT_COUNT,Régulier_PROPERTY_ASSESSMENT_COUNT,HEIGHT_ABOVE_GROUND_MEAN,DWELLING_MEAN,CONSTRUCTION_YEAR_MEAN,LAND_AREA_MEAN,BUILDING_AREA_MEAN
count,34,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000
unique,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,REM33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,14752.676471,5383.970588,9368.676471,1.669252,1.909239,1966.164498,1744.473383,695.843108
std,NaN,11692.637165,6963.531442,7029.162650,0.178831,0.652216,14.510131,2651.686684,501.917888
min,NaN,74.000000,0.000000,74.000000,1.052632,1.000000,1932.048753,218.302654,100.568966
25%,NaN,6179.500000,495.500000,4345.500000,1.555426,1.382603,1960.097888,568.109270,311.566414
50%,NaN,11948.500000,3150.500000,7914.000000,1.678461,1.912559,1968.309573,796.333407,539.633052
75%,NaN,25930.250000,8430.750000,12712.250000,1.812223,2.295534,1978.238618,1291.630669,953.587339
max,NaN,42241.000000,34920.000000,25557.000000,1.906144,3.423563,1983.986846,13474.906615,2226.556192

# Output file

In [82]:
df_fe_stc.to_csv(
    'Data/Processed_Datasets/Combined_tables/df_fe_property_assessments.csv')